### ISSUE TITLE
Exporter fails with panic error

### ISSUE THREAD

**Issue by arbulu89** [SUSE/sap_host_exporter#34]
Hello,

I have found that in a SAP host without HA plugin installed (PAS instance in my case), the exporter enters in a failing loop in every request.

```
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: time="2020-04-07T17:34:59+02:00" level=warning msg="Enqueue Server Collector scrape failed: SAPControl web service error: EnqMon_GetStatistic failed"
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: time="2020-04-07T17:34:59+02:00" level=warning msg="Alert Collector scrape failed: SAPControl web service error: HA product checks not implemented"
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: panic: send on closed channel
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: goroutine 34 [running]:
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: github.com/SUSE/sap_host_exporter/collector/alert.(*alertCollector).recordHACheck(0xc000123080, 0xc00033b400, 0xc00010a960, 0x0, 0xc0001d0380)
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]:         /home/abuild/rpmbuild/BUILD/prometheus-sap_host_exporter-0.3.0+git.1586180171.ad72196/collector/alert/alert.go:92 +0x18c
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: github.com/SUSE/sap_host_exporter/collector/alert.(*alertCollector).recordHAChecks(0xc000123080, 0xc0001dad00, 0x15, 0x20, 0xc00010a960, 0x0, 0x0)
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]:         /home/abuild/rpmbuild/BUILD/prometheus-sap_host_exporter-0.3.0+git.1586180171.ad72196/collector/alert/alert.go:78 +0x63
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: github.com/SUSE/sap_host_exporter/collector/alert.(*alertCollector).recordHAConfigChecks(0xc000123080, 0xc00010a960, 0x0, 0x0)
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]:         /home/abuild/rpmbuild/BUILD/prometheus-sap_host_exporter-0.3.0+git.1586180171.ad72196/collector/alert/alert.go:53 +0x7f
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: github.com/SUSE/sap_host_exporter/collector/alert.(*alertCollector).recordHAConfigChecks-fm(0xc00010a960, 0x0, 0x0)
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]:         /home/abuild/rpmbuild/BUILD/prometheus-sap_host_exporter-0.3.0+git.1586180171.ad72196/collector/alert/alert.go:37 +0x34
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: github.com/SUSE/sap_host_exporter/collector.RecordConcurrently.func1(0xc0001d6060, 0xc00010a960, 0xc0001d2010)
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]:         /home/abuild/rpmbuild/BUILD/prometheus-sap_host_exporter-0.3.0+git.1586180171.ad72196/collector/default_collector.go:65 +0x30
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]: created by github.com/SUSE/sap_host_exporter/collector.RecordConcurrently
Apr 07 17:34:59 netweaver03 sap_host_exporter[31019]:         /home/abuild/rpmbuild/BUILD/prometheus-sap_host_exporter-0.3.0+git.1586180171.ad72196/collector/default_collector.go:64 +0x83
Apr 07 17:34:59 netweaver03 systemd[1]: prometheus-sap_host_exporter@default.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 07 17:34:59 netweaver03 systemd[1]: prometheus-sap_host_exporter@default.service: Unit entered failed state.
Apr 07 17:34:59 netweaver03 systemd[1]: prometheus-sap_host_exporter@default.service: Failed with result 'exit-code'.```

After every error the exporter is restarted automatically.

**Comment by stefanotorresi** [comment]
thanks for the report xabi, I think I know where the issue is.
